#---------------------------------#
#      general configuration      #
#---------------------------------#

# Reset the build number at each minor releases.
version: '1.2.{build}-{branch}'

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

branches:
  only:
  - master

skip_tags: true

skip_branch_with_pr: true

pull_requests:
  do_not_increment_build_number: true

skip_commits:
  files:
    - '**/*.yml'
    - '**/*.fsx'
    - '**/*.cmd'

#---------------------------------#
#    environment configuration    #
#---------------------------------#
image: Visual Studio 2017

environment:
  VisualStudioVersion: 15.0
  BuildConfiguration: release

nuget:
  disable_publish_on_pr: true

#---------------------------------#
#       build configuration       #
#---------------------------------#
build_script:
- .\fake run build.fsx -t All

#---------------------------------#
#       tests configuration       #
#---------------------------------#
test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:
  - path: .\artifacts\**\*.nupkg

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
deploy:
  - provider: NuGet
    api_key:
      secure: w9QUr4WEITnD4d+d/btMV7BbTpz6ZQmHfWOQ6jazhF72gGgXfPSaTp3KgO34YQ6A

  - provider: GitHub
    tag: $(appveyor_build_version)
    description: ''
    auth_token:
      secure: XUe++IN5fwLVTJC5RIWWMswUwAGMlmYBdNevE0rXCUYl8Qv3xGIjwQo3y5+Pn4rF
    artifact: /.*\.nupkg/