version: '{build}'
image: Visual Studio 2017
skip_branch_with_pr: true

skip_commits:
  files:
    - docs/**/*
    - '**/*.md'
    - .gitignore
    - CREDITS
    - LICENSE

pull_requests:
  do_not_increment_build_number: true

environment:
  VisualStudioVersion: 15.0
  BuildConfiguration: release

install:
  - ps: choco install gitversion.portable -pre -y

build_script:
  - ps: .\fake run build.fsx -t All

test: off

artifacts:
  - path: .\artifacts\**\*.nupkg

before_deploy:
  - ps: Write-Output "Looking for previous tag..."
  - ps: $prev_commit=git rev-list --tags --skip=1 --max-count=1
  - ps: Write-Output "Found previous commit: $prev_commit"
  - ps: $prev_tag=git describe --abbrev=0 --tags $prev_commit
  - ps: Write-Output "Found previous tag: $prev_tag"
  - ps: $range=$prev_tag + ".." + $appveyor_repo_tag_name
  - ps: Write-Output "Getting logs for range '$range'"
  - ps: $release_notes=git log --pretty=format:"%h %s" $range
  - ps: Write-Output "Found logs:"
  - ps: Write-Output $release_notes

deploy:
  #- provider: NuGet
  #  api_key:
  #    secure: w9QUr4WEITnD4d+d/btMV7BbTpz6ZQmHfWOQ6jazhF72gGgXfPSaTp3KgO34YQ6A
  #  on:
  #    appveyor_repo_tag: true

  - provider: GitHub
    description: '$(release_notes)'
    release: '$(appveyor_repo_tag_name)'
    artifact: /.*\.nupkg/
    auth_token:
      secure: XUe++IN5fwLVTJC5RIWWMswUwAGMlmYBdNevE0rXCUYl8Qv3xGIjwQo3y5+Pn4rF
    on:
      appveyor_repo_tag: true