version: '{build}'
image: Visual Studio 2017

skip_tags: true
skip_branch_with_pr: true

pull_requests:
  do_not_increment_build_number: true

skip_commits:
  files:
    - '**/*.yml'
    - '**/*.fsx'
    - '**/*.cmd'

environment:
  VisualStudioVersion: 15.0
  BuildConfiguration: release

install:
  - choco install gitversion.portable -pre -y

build_script:
- .\fake run build.fsx -t All

test: off

artifacts:
  - path: .\artifacts\**\*.nupkg

deploy_script:
  - echo Hello in the deployment