#---------------------------------#
#      general configuration      #
#---------------------------------#

# Reset the build number at each minor releases.
version: '{version}'

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

branches:
  only:
  - master

skip_tags: true

skip_branch_with_pr: true

pull_requests:
  do_not_increment_build_number: true

skip_commits:
  files:
    - '**/*.yml'
    - '**/*.fsx'
    - '**/*.cmd'

#---------------------------------#
#    environment configuration    #
#---------------------------------#
image: Visual Studio 2017

environment:
  VisualStudioVersion: 15.0
  BuildConfiguration: release

nuget:
  disable_publish_on_pr: true

#---------------------------------#
#       build configuration       #
#---------------------------------#
# install:
  # - choco install gitversion.portable -pre -y

install:
  # - ps: gitversion /l console /output buildserver /updateAssemblyInfo
  - ps: appveyor version "1.1.1-test"

build_script:
- .\fake run build.fsx -t All

#---------------------------------#
#       tests configuration       #
#---------------------------------#
test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:
  - path: .\artifacts\**\*.nupkg