version: '{build}'

branches:
  only:
  - master

skip_tags: true

skip_branch_with_pr: true

nuget:
  disable_publish_on_pr: true

build_script:
- ps: .\Build.ps1

test: off

artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet

image: Visual Studio 2017

configuration: Release

environment:
  VisualStudioVersion: 15.0