version: '{build}'
image: Visual Studio 2017

skip_tags: true
skip_branch_with_pr: true
skip_commits:
  files:
    - docs/**/*
    - '**/*.md'
    - .gitignore
    - CREDITS
    - LICENSE
    - '**/*.fsx'

pull_requests:
  do_not_increment_build_number: true

environment:
  VisualStudioVersion: 15.0
  BuildConfiguration: release
  BuildEnvironment: appveyor

install:
  - choco install gitversion.portable -pre -y

build_script:
- .\fake run build.fsx -t All

test: off