#---------------------------------#
#      general configuration      #
#---------------------------------#
version: '{build}'

branches:
  only:
  - master
  
skip_tags: true

skip_branch_with_pr: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#
image: Visual Studio 2017

environment:
  VisualStudioVersion: 15.0
  BUILD_CONFIGURATION: release

nuget:
  disable_publish_on_pr: true

#---------------------------------#
#       build configuration       #
#---------------------------------#
build_script:
- .\fake run build.fsx

#---------------------------------#
#       tests configuration       #
#---------------------------------#
test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet